apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/PLt6Crm0wCks1IRUX84MaEQSK5gzRQtXx2V8v0vixfCTqRu,iv:6wkMSThjgb4nqtuEi6mlWwpU1YAWAyP0DuWG78bFHgs=,tag:eE05sNykNC+SWSiLSXuTyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Zp7YZQErHrXEfHWDc+lo4HpovLyR9GCTNLRj4qN3QGX60AhB+MB/27pRFj/MaJQUdX5a6QMuE7PhwlGlC91+/YKq7+V77Jo7C33hIg+s2slCcNU21vWWvWKaWQTq9IER1iWVZcTX13PFVmkPIudY3frlO95JoHCPVU7CMGmeW4cs8k0lFYumozD2Wj0mgEZuD41Gj34v2s3BZmgOtvzJKp8T5/uMJWSzX0nUueYf9A==,iv:j1iDDR2TfVnYPU/K/SQb92Yt8uZ3dMTxNbQCKi/qvW8=,tag:zxHVsOjTazO3O9ElMAa0WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK0l3WmhRWTY2SEYzWnRk
            eXF4TWxab2gxb1JBbElVQXlLTXd0UVZqd0FRCjhEWUFNT0tCd25VY09kUFpTd3dF
            b0daVU9kQlBsZkpWVE5qTW52U2doN28KLS0tIFBNWEtkODlud0dpZm5qVVFmcmti
            b00xc2pzU0ErdS9BQXF1cy9NSitmZUUKG/kb4T6U5COcf+Uzd2Bk/5a2x0Lx8APf
            lF+rNjxo4uwU0X2CTM0oS0PtFKryzA3QsYyk6BdnRXvAgQcYjTIbWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T11:56:29Z"
    mac: ENC[AES256_GCM,data:Sn7f6XFToOPm4FwSbt4kSOENaf7GcGz9QvpZ5Yc+lVIzngzjWEYOGJ/W5i4mKfET4zqdkepyN51pk4t43L7qastmyF3fLAyi0YPXryX9Zukc/coyh8SmpPqUulSdyQ8FpM9geMNM/oZ4T4PT1tRH4foSfESyKKxLpght+CtNcAs=,iv:3WuAZZKkXAdSBVsUSIBsvKdbc3icnPKkhdoI5CpZ5ZM=,tag:V1x+qTxP9BtewBMgWQrtVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
