apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:W4wkKaRHTMdyqGNxep0SMhF5jqUrnxTwqH92UHXtnzc2VeIf,iv:5D1CTfJ5dbY7YQ5Xd4EL+BGS3xfeMsa46M1MPb+NmYw=,tag:OSAyzXj2kUa3hmHwDHGELQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:VSUzPeZS3Z4WPoqa4cACJdwOUxHSBy3kTwRjAJ4+6zSudSDZg/Nmvuiv2T8YoaSx4esTPvhpn6kpavKKZH8SE2BmqJmJEjtWgaEVLLwi91lwmKwbFljszP3zOEe3v4tlKrwszuWJ7wfrzoRhJeF8zvCNHe3jZudU7fE4NWmsOaIRJROUD7NiP/aJWu4+4xx5s5+PSbm/ztyRNScbSn7F8M94jTOMHOrjaHPHUfZ4zA==,iv:guC4xF2sg7PVWk7vnhEXq0RN3vf07UtsGU4XTVPEUGc=,tag:FzTwQqitis/oliz5Oh2GlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRS9iam9QclZCNVNtRUkx
            M2ZqbStKS3FZclF6KzA1cFJHMHNDMmkvekNFCnd6aE94SjZxbGo3QVNSREVPMUtF
            ckpLOGhLMXRQblpXdEtzTXJHZFB4NDQKLS0tIDYzMzdPWUtOeW1rV3R1dXpFL0wy
            Qk9ScUxMWk9UZjV2VlF2NjdSbHdJK1kKruwWZnh5K1yOD9eXQ/umsNZrxpXv/nrH
            rw3NXyKRIvmn75/AR8eHn/6zOPSxVNOdVmcKY+EX2WknuhKMmtg3lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T12:18:07Z"
    mac: ENC[AES256_GCM,data:8EMawccxDp0YJ+LlaaNqwA+OxC4/rg+8hE0osOY/q824w/l1HmYi3mg+a7DjrI74OAHWqidqkZplIttFvhsyWdzrq+wuuqZ2BQ39/qH8btYTxfT/P125e+f+cAd8EAi/35UjvePsPSehOMx1JkV+q+8Bb+/VCgglTXsIDN3jSwE=,iv:tUoUIV1UTfggwfS82XTq2zFMGzZWh0z/len1P2toQNo=,tag:TH2mLHtMrbYakAJbjRrQjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
