apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:pY0Hs3QGBwlliEOl/GOwy4/GDCXs469AdkmwA1v2QbQ=,iv:Nzz1jof6O7Ey1YcfyYm4rLZOvuYOkNJZMKMnSW98R9A=,tag:UfSDsw9T/IQY6ImWzslPIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MEk5SXVQUysvUXNkWXNk
            U29JLzVlczUzeFlTcGxiTmRpNG8yZ3VKMmhjClNCZ2VSNUdib21zQVFNNTMvcFo4
            UDlZRzltWWlOUUs2VDROSVpTek1yVncKLS0tIHFpVENFakxaTHNEaWVXY2IvRWpG
            Qk5PMTRZcVFqcGFqK0lWMm9LSWVrZUEKMIWBk9a2ezlOuyDiteM23ipdrY8hEfEC
            ZFl8v/nkTDzkV6i15Oaw0CscQDOXGIjFp8LXmdjInT/a/ADDiVG/Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T11:53:35Z"
    mac: ENC[AES256_GCM,data:lciz+lQQNcvXlrKGL7EVSZ0YyMY6NIFG7qENCFQu5QYe6sXX1W/09OGjqEaByFF/possIWJj3vmmdekLGqfQq/GvkqdvReh348V/E084FDH9RYVfvNIqTvLNrLsdgD10jLymy52leAzt46nCNne8fgak/CuXx5fNBCGpItYXmtk=,iv:Mlcaxck5byJ4tJRpnTmg5hBrbs80J9ailhjUeYWxj6A=,tag:KgUxumhuNCtrZfpkEJ5G5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
