apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:F1NrYjTB8BY7quR9WdcScbcjVea0LkjxTBz6ZKGdEFI1RVdxlMWpKw==,iv:Mkrhq8+HV21ReAdBW0WjmQPf25jtSw/wiYLo+W3nLdo=,tag:BrfteEVOmVY9LdmIbyAKvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8u26jxxx3ls68u6sy03udtex6wzen0vqx28qesg95752n9uksfqv947sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY2twZHkxUVV2TjNuNkZn
            UkVaYkRXZEJGUXRGTkhXYnc4eU90MjMvSkdVCjliMk1wa2dZTklxdnFKUGE4dG9m
            cWJvZFVCdDVPTGRYU2cxQ1dlVktjUFkKLS0tIGdsOVNiMzI0N3VFYzZqd3dSOC9j
            RUVhQVdsTkhRUkhWNlZWajlxMWZrK0kKCVPbbFC6mn0lTeiRtitVYrES6rVNjJYt
            GrYTwsb5GGixCEQNzqaaoFxJ5sKgoueb45LeoOfr3LBL0uMBdLNiBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T11:53:35Z"
    mac: ENC[AES256_GCM,data:jXdQ/6eFhzleIas0C7qSBw4FZoWKTwzVJp4TohXROgjL/MzNTuU5u7NnX7gwbmjUQWZsSAdkryfije2FOEMxq2YQLFi8q4M05h60uatwXOhiIxQXM1inwrdC60/eOt1RGKDUVgGtX6WZAnOAn1MKSwnYOxczU+4/N/n4r5FXu4E=,iv:dk3+g7erMP0spuYi1w+DO/sNx9ifQboO0/PJYh3LdoE=,tag:0gSg7A3z8WjHkBETV8pKQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
